## Prediction File for ANN Model
---

In [2]:
import tensorflow as tf
from tensorflow.keras.models import load_model

import pandas as pd 
import numpy as np
import pickle

WARNING:tensorflow:From d:\CODE\ANN Classification\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

> Loading Pickle file
---

In [3]:
# Trained Model
model = load_model('models/models.h5')

# Encoder
with open('models/onehot_encoder_geo.pkl', 'rb') as file:
    onehot_encoder_geo = pickle.load(file)

# Gender
with open('models/label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

# Scaler
with open('models/scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

WARNING:tensorflow:From d:\CODE\ANN Classification\venv\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

> New Input Data
---

In [4]:
input_data = {
    'CreditScore':600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

input_df= pd.DataFrame([input_data])

> Encoding Categorical Variable: Gender
---

In [5]:
input_df['Gender'] = label_encoder_gender.transform([input_data['Gender']])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

> OHE: Geography
---

In [6]:
geo_encoded = onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

d:\CODE\ANN Classification\venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0